BeerCellier/Controllers/AuthenticationController.cs
using BeerCellier.Models;
using System.Web.Mvc;
using BeerCellier.Entities;
using BeerCellier.Core;

namespace BeerCellier.Controllers
{
    public class AuthenticationController : Controller
    {
        private readonly IPersistenceContext _persistenceContext;
        private readonly ISessionContext _sessionContext;

        public AuthenticationController(IPersistenceContext persistenceContext, ISessionContext sessionContext)
        {
            _persistenceContext = persistenceContext;
            _sessionContext = sessionContext;
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]       
        [ValidateAntiForgeryToken]
        public ActionResult Login([Bind(Include = "Username,Password")] LoginViewModel model, string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;

            if (!ModelState.IsValid)
            {
                return View(model);
            }           

            if (!_sessionContext.SignIn(model.Username, model.Password))
            {
                ModelState.AddModelError(string.Empty, "Username or password is invalid.");
                return View(model);
            }

            if (Url.IsLocalUrl(ViewBag.ReturnUrl))
            {
                return Redirect(ViewBag.ReturnUrl);
            }            
            
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register([Bind(Include = "Username,Password")] RegisterViewModel model, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = new User(model.Username, model.Password);

            _persistenceContext.Add(user);
            _persistenceContext.SaveChanges();

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult Logout()
        {
            _sessionContext.signOut();            
            return RedirectToAction("Index", "Home");
        }
    }
}

BeerCellier/Controllers/CellarController.cs
using BeerCellier.Core;
using BeerCellier.Entities;
using BeerCellier.Models;
using BeerCellier.Queries;
using PagedList;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace BeerCellier.Controllers
{
    [Authorize]
    public class CellarController : Controller
    { 
        private readonly IPersistenceContext _persistenceContext;
        private readonly ISessionContext _sessionContext;
        public int PageSize { get; }       

        public CellarController(IPersistenceContext persistenceContext, ISessionContext sessionContext, int pageSize)
        {
            _persistenceContext = persistenceContext;
            _sessionContext = sessionContext;
            this.PageSize = pageSize;
        }

        // GET: Cellar
        public ActionResult Index(string searchTerm, int? page)
        {
            var query = _persistenceContext.Query<Beer>().ForUser(_sessionContext.GetCurrentLoggedUser());            

            if (!string.IsNullOrWhiteSpace(searchTerm))
            {               
                query = query.Where(b => b.Name.Contains(searchTerm));
            }
           
            query = query.OrderBy(b => b.Name);

            var pageNumber = page ?? 1;
            var model = query.ToViewModels().ToPagedList(pageNumber, PageSize);

            if (Request.IsAjaxRequest())
            {
                return PartialView("_BeerList", model);
            }

            return View(model);
        }

        // GET: Cellar/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var beer = _persistenceContext.Query<Beer>().FindById(id.Value);
            
            if (beer == null)
            {
                return HttpNotFound();
            }

            var model = new BeerViewModel(beer);

            return View(model);
        }

        // GET: Cellar/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cellar/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,Quantity")] CreateBeerViewModel model)
        {
            if (ModelState.IsValid)
            {
                var beer = new Beer
                {
                    Quantity = model.Quantity,
                    Name = model.Name,
                    Owner = _sessionContext.GetCurrentLoggedUser()
                };

                _persistenceContext.Add(beer);
                _persistenceContext.SaveChanges();

                TempData["messageInfo"] = "Your beer has been added.";

                return RedirectToAction("Index");          
            }

            return View(model);
        }

        // GET: Cellar/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var beer = _persistenceContext.Query<Beer>().FindById(id.Value);

            if (beer == null)
            {
                return HttpNotFound();
            }

            var model = new EditBeerViewModel(beer);

            return View(model);
        }

        // POST: Cellar/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Quantity")] EditBeerViewModel model)
        {
            if (ModelState.IsValid)
            {
                var beer = _persistenceContext.Query<Beer>().FindById(model.ID);

                if (beer == null)
                {
                    return HttpNotFound();
                }

                beer.Name = model.Name;
                beer.Quantity = model.Quantity;
                
                _persistenceContext.SaveChanges();

                TempData["messageInfo"] = "Your modifications has been saved.";

                return RedirectToAction("Index");
            }

            return View(model);
        }

        // GET: Cellar/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var beer = _persistenceContext.Query<Beer>().FindById(id.Value);

            if (beer == null)
            {
                return HttpNotFound();
            }

            var model = new BeerViewModel(beer);            

            return View(model);
        }

        // POST: Cellar/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete([Bind(Include = "ID")] DeleteBeerViewModel model)
        {
            Beer beer = _persistenceContext.Query<Beer>().FindById(model.ID);

            if (beer == null)
            {
                return HttpNotFound();
            }

            _persistenceContext.Remove(beer);
            _persistenceContext.SaveChanges();

            TempData["messageInfo"] = "Your beer has been deleted.";

            return RedirectToAction("Index");
        }

        // GET: Cellar/Drink/5
        public ActionResult Drink(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var beer = _persistenceContext.Query<Beer>().FindById(id.Value);

            if (beer == null)
            {
                return HttpNotFound();
            }

            var model = new BeerViewModel(beer);

            return View(model);
        }

        // POST: Cellar/Drink/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Drink([Bind(Include = "ID")] DrinkBeerViewModel model)
        {
            Beer beer = _persistenceContext.Query<Beer>().FindById(model.ID);

            if (beer == null)
            {
                return HttpNotFound();
            }

            beer.Quantity -= 1;

            if (beer.Quantity < 0)
            {
                beer.Quantity = 0;
            }
            
            _persistenceContext.SaveChanges();

            TempData["messageInfo"] = "Your modifications has been drinked.";

            return RedirectToAction("Index");
        }

        // GET: /Cellar/QuickSearch?term=
        public ActionResult QuickSearch(string term)
        {
            var model = _persistenceContext.Query<Beer>()
                .Search(_sessionContext.GetCurrentLoggedUser(), term)
                .Take(10)
                .Select(b => new {
                    label = b.Name
                });

            return Json(model, JsonRequestBehavior.AllowGet);
        }   
    }    
}

BeerCellier/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - BeerCellier</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("BeerCellier", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("My Cellar", "Index", "Cellar")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>                
                <ul class="nav navbar-nav navbar-right">
                    @if (Request.IsAuthenticated)
                    {                        
                        <li>@Html.ActionLink("Logout", "Logout", "Authentication")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Register", "Register", "Authentication")</li>
                        <li role="separator" class="divider"></li>
                        <li>@Html.ActionLink("Login", "Login", "Authentication")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @if (TempData["messageInfo"] != null)
        {
            <div class="alert alert-success alert-dismissible fade in" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                @TempData["messageInfo"]
            </div>
        }
        @RenderBody()
        <hr>
        <footer>
            <p>&copy; @DateTime.Now.Year - Yan Pearson</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/app")
    @Scripts.Render("~/bundles/jqueryui")
    @RenderSection("scripts", required: false)
</body>
</html>